language: scala
jdk:
- oraclejdk8
scala:
- 2.11.8
env:
  global:
    secure: lkzyqUUhXwQw30Ivm5E8kX67txk/pUr15EzdW++K1aX06bzCPY8szGHPVh4YejOpuz6ORvo2LyTTKlOadW1BrA3vVwfrNutDLv33VNisLnMlLtJT326ytW17yHgsCLlO2IFd13APv7txpFmhBKICeezFaZbrKhOiWeTcz2yl/FSxlmUBjEjJPlxcXc8rcqSh6K74qkHLRny9IgjQGZljhg4PUrgPzEop+hGPdxiEqliNZcxR83cLxI776TUc22Tu4PxpWM/Okr4yDMu9sTaAsxJ165+UK0wt1okei270hvEeDRHo2om8q8vNrjaDUnzwCzHaog30+fZXhNUR8fKkpcUzmWLWRJQSYq73GlwBpfEwLoZQWIgHJHBb5HUYpJ/HeHuvUmmBHlgjKRisV/HGi15jYi/fj5dtf7tmJNv0VLXsZnhkkro9UtOrdAUSfK35D1KrXY52lPQRQ1IJAHeOKYpefwEEuL9q4XQDLzIBj4AmGPNpEmYGUnU/yNIwkfB3JzZEENhLDKU2f94UAdACBsYN/Mw5gV0Qb2YBrMOjJPeLkd7xtD65YuJ6oJ+9rz83RdhQMjRWDRLQF2/PtA6FTGAhhrjck9Ev/crlqLKTY1SdtETWDO/KPugpvcBQAP/Fp8veY/cDXzPuvCEe4NBKMEkrBO9PVK5p5DtwObZiBhk=
script: sbt clean coverage test
after_success: sbt coverageReport coveralls
